# Generated by Django 6.0.6 on 2026-06-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Jokes",
            new_name="Joke",
        ),
    ]
