# Generated by Django 6.0.5 on 2026-05-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(blank=True)),
                ("display_name", models.TextField(blank=True)),
                ("profile_image_url", models.TextField(blank=True)),
                ("bio_text", models.TextField(blank=True)),
                ("join_date", models.DateField(blank=True)),
            ],
        ),
    ]
