# Generated by Django 6.0.5 on 2026-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0007_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
