# Generated by Django 6.0.5 on 2026-06-18 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorite_movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorited_by_profiles",
                to="project.movie",
            ),
        ),
    ]
